language: python
python:
  - "3.8"

branches:
  only:
  - /.*/

install:
  - pip install -r requirements.txt

script:
  - sh ratenyu/util/management/commands/create_log_folder.sh
  - black ratenyu/
  - ratenyu/manage.py makemigrations
  - ratenyu/manage.py migrate
  - coverage run ratenyu/manage.py test search.tests users.tests professors.tests courses.tests

after_success:
  coveralls

before_deploy:
  - |
    if [[ $BRANCH == develop ]]; then
      rm .ebextensions/django_prod.config
    fi
  - |
    if [[ $BRANCH == master ]]; then
      rm .ebextensions/django_dev.config
    fi

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "ratenyu"
    env: "$EB_ENV"
    bucket_name: "elasticbeanstalk-us-east-1-384537145874"
    on:
      branch: $BRANCH
      condition: $BRANCH = develop || $BRANCH = master
