language: python
python:
  - "3.8"

branches:
  only:
  - /.*/

install:
  - pip install -r requirements.txt

script:
  - black ratenyu/
  - ratenyu/manage.py makemigrations
  - ratenyu/manage.py migrate
  - coverage run ratenyu/manage.py test courses.tests
  - coverage run ratenyu/manage.py test professors.tests

after_success:
  coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-1"
    app: "ratenyu"
    env: "$EB_ENV"
    bucket_name: "elasticbeanstalk-us-east-1-384537145874"
    on:
      branch: $BRANCH
      condition: $BRANCH = develop || $BRANCH = master
