branch-defaults:
  default:
    environment: null
    group_suffix: null
  develop:
    environment: ratenyu-dev
  master:
    environment: ratenyu
    group_suffix: null
global:
  application_name: ratenyu
  branch: null
  default_ec2_keyname: AppSecVM
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-team4
  repository: null
  sc: null
  workspace_type: Application
