# Generated by Django 4.1.2 on 2022-10-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetails",
            old_name="stiudent_status",
            new_name="student_status",
        ),
    ]
