# Generated by Django 4.1.2 on 2022-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_stiudent_status_userdetails_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="account_registered",
            field=models.BooleanField(default=False),
        ),
    ]
