# Generated by Django 4.1.2 on 2022-11-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userdetails_account_registered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="account_registered",
        ),
    ]
